### ISSUE TITLE
Problem executing large cells: truncated commands

### ISSUE THREAD

**Issue by arntanguy** [daeyun/vim-matlab#19]
Hi,

It seems that there is an issue when executing cells with a large amount of Matlab code.
The commands get truncated, which causes Matlab to fail executing them.

I haven't had time to investigate this further, but I wrote a dirty quick hack for my own purposes that splits large commands at each ";": arntanguy/vim-matlab@de5b71429189188e753b2e3cdac4a1052d663da3

There obviously has to be a better solution, but I don't have time to investigate.

**Comment by daeyun** [comment]
Turns out Matlab's command prompt doesn't allow lines longer than 4096.
I think it is fixed in 31c7f0b.

**Comment by arntanguy** [comment]
Thanks, I used it for the last two days without any issues, looks like this solves the issue.
