### ISSUE TITLE
E492: Not an editor command: MatlabCliRunSelection 

### ISSUE THREAD

**Issue by mesneym** [daeyun/vim-matlab#20]
Hi, 
When I try to run the matlab code using C-m, i get an error saying "not an editor command." However, insert mode commands seem to work pretty well.

**Comment by mesneym** [comment]
Any help is greatly apprieciated

**Comment by mesneym** [comment]
Any help is greatly appreciated

**Comment by daeyun** [comment]
When happens when you run :MatlabCliRunCell ? Do other commands work?

**Comment by mesneym** [comment]
No, it doesn't work. Same response
E492: Not an editor command: MatlabCliRunCell .

**Comment by mesneym** [comment]
However, the C-I command works

**Comment by mesneym** [comment]
MatlabNormalModeCreateCell

**Comment by daeyun** [comment]
Do you have the python3 neovim package installed? How did you install vim-matlab? Did you run :UpdateRemotePlugins after installing?

**Comment by mesneym** [comment]
yes. I already had neovim installed and I have used other plugins before. Also did update the plugins after installing.

**Comment by daeyun** [comment]
I suspect that the python part of the plugin is not recognized somehow. `MatlabNormalModeCreateCell` is defined in vimscript and doesn't use python.

Can you try the commands in https://github.com/daeyun/vim-matlab/blob/master/rplugin/python/vim_matlab/__init__.py ? e.g. `MatlabPrintCellLines`, `MatlabRename`, etc

**Comment by mesneym** [comment]
Still giving me the same response. Not an editor command.

**Comment by daeyun** [comment]
I can't reproduce the issue. I'm using Neovim 0.2.0, python2-neovim 0.1.13 (not python3, sorry), and ubuntu 16.04. Do you see any warnings when you edit the matlab file with neovim?

**Comment by mesneym** [comment]
No, i don't get any warnings.

**Comment by daeyun** [comment]
what versions of neovim and python neovim client are you using?

**Comment by mesneym** [comment]
python 2.7.13 
neovim-0.1.13

**Comment by tdy** [comment]
Do your other python plugins work properly at this moment? It really sounds like there's a disconnect between your neovim and python right now.

I would run `:UpdateRemotePlugins` again just for completeness. Also just to clarify, this isn't the same thing as updating with a plugin manager (e.g., vim-plug's `:PlugUpdate`). It's a neovim-specific command.

**Comment by mesneym** [comment]
Yes. I have deoplete which is configured to work with python3 and it works fine. Also I did do :UpdateRemotePlugins still gave me the same results.

**Comment by mesneym** [comment]
remote/host: Python3 host registered plugins('deoplete')
remote/host: python host registered plugins('vim-matlab')
remote/host: generate rplugin manifest home/username/.local/share/nvim/rplugin.vim

**Comment by mesneym** [comment]
It now works.  I reinstalled it and  repeated the same procedure. I just don't know what went wrong.
