### ISSUE TITLE
Run in neovim terminal buffer doesn't work (matlab_server_launcher = 'vim')

### ISSUE THREAD

**Issue by mizhozan** [daeyun/vim-matlab#35]
Hi, 

I'm trying to use matlab built-in terminal buffer instead of tmux (or even split horizontally instead of vertical) and none of the below configurations works. neovim still complain that I need to run inside tmux which I've added these configurations.

```vimscript
let g:matlab_server_launcher = 'vim'  "launch the server in a Neovim terminal buffer

let g:matlab_server_split = 'horizontal' "launch the server in a horizontal split
```

**Comment by tdy** [comment]
What do `:echo g:matlab_server_launcher` and `:echo g:matlab_server_split` show? And what is the full error message?

**Comment by mizhozan** [comment]
Sorry for very late response, I stopped using this plugin (including Matlab) and right now don't have the environment to reproduce it. So I'll close the issue at the moment.
