### ISSUE TITLE
InsertEnter throws KeyError: 'last_written'

### ISSUE THREAD

**Issue by tdy** [daeyun/vim-matlab#9]
I get this error every time I open a file and enter insert mode. [`InsertEnter`](https://github.com/daeyun/vim-matlab/blob/c53b138/rplugin/python/vim_matlab/__init__.py#L240) tries to read `buffer_state[path]['last_written']`, which only exists if a [`BufWrite`](https://github.com/daeyun/vim-matlab/blob/c53b138/rplugin/python/vim_matlab/__init__.py#L252) event has previously occurred.

```
error caught in async handler '/Users/tdy/.vim/plugs/vim-matlab/rplugin/python/vim_matlab:autocmd:InsertEnter:*.m ()'
Traceback (most recent call last):
  File "/Users/tdy/.vim/plugs/vim-matlab/rplugin/python/vim_matlab/__init__.py", line 242, in insert_enter
    self.refresh_buffer()
  File "/Users/tdy/.vim/plugs/vim-matlab/rplugin/python/vim_matlab/__init__.py", line 258, in refresh_buffer
    last_written = self.buffer_state[path]['last_written']
KeyError: 'last_written'
```

**Comment by daeyun** [comment]
Looks like this is fixed, worked on my end. Thanks
